# Travis CI build configuration

# branch safelist
branches:
  only:
    - /.*/

env:
  - GODOT_VERSION="3.1.1"

before_install:

  - ls -l

  # install dependencies

  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends ca-certificates
  - sudo apt-get install -y --no-install-recommends git
  - sudo apt-get install -y --no-install-recommends python
  - sudo apt-get install -y --no-install-recommends python-openssl
  - sudo apt-get install -y --no-install-recommends unzip
  - sudo apt-get install -y --no-install-recommends wget
  - sudo apt-get install -y --no-install-recommends zip

  - sudo rm -rf /var/lib/apt/lists/*

  # install headless godot & export templates

  - wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
  - wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz

  - mkdir -p ~/.config/godot
  - mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.stable

  - unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
  - sudo mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 /usr/local/bin/godot
  - unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
  - sudo mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}.stable
  - sudo rm -f Godot_v${GODOT_VERSION}-stable_export_templates.tpz Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip

script:
  - godot --export "Windows Desktop" ./build/astral-win.exe
  - godot --export "Mac OSX" ./build/astral-mac.dmg

# github tagged releases

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: 
    - "./build/astral-win.exe"
    - "./build/astral-win.pck"
    - "./build/astral-mac.dmg"
  skip_cleanup: true
  on:
    tags: true
